### ISSUE TITLE
Question: How does people submit new stuff? 

### ISSUE THREAD

**Issue by JaDogg** [meSingh/git.wtf#11]

**Comment by meSingh** [comment]
Hi @JaDogg, If you would like to submit an article, you can simply do it by adding a new markdown file in the [content directory](https://github.com/meSingh/git.wtf/tree/develop/content/posts). I will soon write down a proper howto on this. 

For now, you can also mail it to me directly or post it here too.

**Comment by JaDogg** [comment]
Cool. :)
