### ISSUE TITLE
Improve Search System.

### ISSUE THREAD

**Issue by meSingh** [meSingh/git.wtf#7]

**Comment by Wonskcalb** [comment]
I do have an example where the search system is broken. Breaks very often btw https://git.wtf/?query=fixup

**Comment by meSingh** [comment]
Thanks, @Wonskcalb for pointing this out. I've been thinking about integrating a better search something like Algolia just haven't been able to get to it. 

Will try to do it as soon as I can.

**Comment by meSingh** [comment]
Fixed in https://github.com/meSingh/git.wtf/commit/664ebdec2d9d2a1d0f9614cfeb679dbca3232789
